version: "3.8"

services:
  redis:
    container_name: ${CONTAINER_NAME}
    image: redis:alpine
    restart: always
    working_dir: ${WORKING_DIR}
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./data:/data
#      - ./conf:/etc/redis/
#      - ./conf/conf.d:/etc/redis/conf.d
      - ./logs:/var/log/redis
#    command: redis-server ${CONFIG_DIR}/${CONFIG_FILE}