services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
#    volumes:
#      - redis-data:/data
#      # In case if you want to use your own redis.conf
#      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
#    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  #volumes:
#  redis-data:
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - redis-insight-data:/data
    ports:
      - ${REDIS_INSIGHT_PORT:-5540}:5540

volumes:
  redis-insight-data: